19 add the ability to set the recurrence of cycle in month and years not just days
OpenG2P/openg2p-program pull request #8
Opened 2023-01-02 06:25 UTC by reichie020212

2023-01-02 06:37 UTC, jeremi requested changes
Where are the tests?

2023-01-03 01:41 UTC, jeremi requested changes

2023-01-03 01:41 UTC, jeremi commented on g2p_programs/__manifest__.py
> +            "freezegun",
Freezegun is just needed for running the tests, so it should not be needed here.

2023-01-03 01:41 UTC, jeremi commented on g2p_programs/tests/test_cycle_manager_new_cycle.py
> +        self.assertEqual(first_cycle.start_date, datetime.now().date())
This should not be the case as `datetime.now()` is not the first Monday of the month, no?
Also do not use `datetime.now()` but hardcode the dates or use constants

2023-01-03 01:41 UTC, jeremi commented on g2p_programs/tests/test_cycle_manager_new_cycle.py
> +        self.assertEqual(first_cycle.start_date, datetime.now().date())
Dec 15th is not a Monday

2023-01-09 04:48 UTC, jeremi commented
@reichie020212 
- Rename `Cycle Duration` to `Recurrence`
- If I leave the default settings (30 days) why did the cycle start yesterday? That is a bug.
- By default set it monthly on the 1st
- Is there is missing recurrence config for yearly?

2023-01-13 11:04 UTC, reichie020212 commented
> @reichie020212
> 
> * Rename `Cycle Duration` to `Recurrence`
> * If I leave the default settings (30 days) why did the cycle start yesterday? That is a bug.
> * By default set it monthly on the 1st
> * Is there is missing recurrence config for yearly?

@jeremi finished the following:
- renaming
- modify default values
- fixed bug

Upon checking, there is no missing recurrence config for yearly.

2023-01-20 02:34 UTC, jeremi approved these changes

2023-01-20 11:18 UTC, gonzalesedwin1123 approved these changes

2023-01-23 14:42 UTC, shibu-narayanan approved these changes

2023-01-23 14:43 UTC, merged